services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: bdEfren
      POSTGRES_USER: efren
      POSTGRES_PASSWORD: Strongpa$$w0rd!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  uttt-micro-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bdEfren;Username=efren;Password=Strongpa$$w0rd!;
    depends_on:
      - postgres

volumes:
  postgres_data:
