// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.MicroServicios.Autor.Api.Application;

#nullable disable

namespace Tienda.MicroServicios.Autor.Api.Migrations
{
    [DbContext(typeof(WriteDBContext))]
    partial class WriteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tienda.MicroServicios.Autor.Api.Model.AutorLibro", b =>
                {
                    b.Property<string>("AutorLibroGuid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AutorLibroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AutorLibroGuid");

                    b.ToTable("AutorLibro", (string)null);
                });

            modelBuilder.Entity("Tienda.MicroServicios.Autor.Api.Model.GradoAcademico", b =>
                {
                    b.Property<int>("GradoAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GradoAcademicoId"));

                    b.Property<string>("AutorLibroGuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AutorLibroId")
                        .HasColumnType("int");

                    b.Property<string>("CentroAcademico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaGrado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GradoAcademicoGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GradoAcademicoId");

                    b.HasIndex("AutorLibroGuid");

                    b.ToTable("GradoAcademico");
                });

            modelBuilder.Entity("Tienda.MicroServicios.Autor.Api.Model.GradoAcademico", b =>
                {
                    b.HasOne("Tienda.MicroServicios.Autor.Api.Model.AutorLibro", "AutorLibro")
                        .WithMany("GradosAcademicos")
                        .HasForeignKey("AutorLibroGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorLibro");
                });

            modelBuilder.Entity("Tienda.MicroServicios.Autor.Api.Model.AutorLibro", b =>
                {
                    b.Navigation("GradosAcademicos");
                });
#pragma warning restore 612, 618
        }
    }
}
